name: "Test commits"
on: push
jobs: 
    test-commit:
        runs-on: ubuntu-slim
        steps:
          - uses: actions/checkout@v6
          - uses: actions/setup-node@v6
            with:
              node-version: "lts/*"
          - name: "install deps"
            run: "npm ci"
          - name: "run npm-test"
            run: "npm test"